-- Run this script in Supabase SQL Editor before starting the API.
-- The API uses the service role key, while RLS blocks direct client access.

create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'user-resumes',
  'user-resumes',
  false,
  2097152,
  array['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/rtf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique check (email = lower(email)),
  name text not null,
  role text not null check (role in ('candidate', 'recruiter')),
  profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users add column if not exists profile jsonb not null default '{}'::jsonb;

create table if not exists public.user_employment_details (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  is_current boolean not null default false,
  employment_type text check (employment_type in ('Full Time', 'Part Time')),
  company_name text not null,
  job_title text not null,
  joining_date date,
  relieving_date date,
  ctc text,
  skills text[] not null default '{}',
  job_profile text,
  notice_period text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_major_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  project_title text not null,
  company_name text,
  client_name text,
  status text check (status in ('In progress', 'Finished')),
  worked_from date,
  worked_till date,
  project_details text,
  created_at timestamptz not null default now()
);

create index if not exists user_employment_details_user_idx on public.user_employment_details (user_id, created_at);
create index if not exists user_major_projects_user_idx on public.user_major_projects (user_id, created_at);

create table if not exists public.otp_codes (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  otp_hash text not null,
  role text not null check (role in ('candidate', 'recruiter')),
  expires_at timestamptz not null,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists otp_codes_email_sent_at_idx on public.otp_codes (email, sent_at desc);

create table if not exists public.jobs (
  id bigint primary key,
  title text not null,
  company text not null,
  location text not null,
  type text not null,
  salary text,
  featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.career_portals (
  slug text primary key,
  company_name text not null,
  industry text not null,
  career_url text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.job_feed_items (
  id text primary key,
  source text not null,
  source_id text not null,
  title text not null,
  company text not null,
  location text not null default '',
  type text not null default 'Not specified',
  job_type text,
  employment_type text,
  preferred_shift text,
  description text not null default '',
  salary text,
  url text not null,
  posted_at timestamptz,
  fetched_at timestamptz not null default now()
);

create index if not exists job_feed_items_fetched_at_idx on public.job_feed_items (fetched_at desc);
create index if not exists job_feed_items_company_idx on public.job_feed_items (company);

create table if not exists public.user_job_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  job_id text not null,
  job_source text not null,
  job_snapshot jsonb not null,
  applied_at timestamptz not null default now(),
  unique (user_id, job_id)
);

create index if not exists user_job_applications_user_applied_idx on public.user_job_applications (user_id, applied_at desc);

create table if not exists public.library_topics (
  id bigint generated by default as identity primary key,
  name text not null unique,
  brief_description text not null,
  explanation text not null,
  example text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists library_topics_name_idx on public.library_topics (name);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null unique,
  topic text not null,
  provider text not null,
  level text not null,
  duration text not null,
  url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists courses_topic_title_idx on public.courses (topic, title);

alter table public.users enable row level security;
alter table public.user_employment_details enable row level security;
alter table public.user_major_projects enable row level security;
alter table public.otp_codes enable row level security;
alter table public.jobs enable row level security;
alter table public.career_portals enable row level security;
alter table public.job_feed_items enable row level security;
alter table public.user_job_applications enable row level security;
alter table public.library_topics enable row level security;
alter table public.courses enable row level security;

delete from public.jobs where company in ('NovaLabs', 'Streamline AI', 'Motive Studio', 'PixelForge', 'BluePeak');

delete from public.career_portals where slug not in (
  'tcs', 'infosys', 'hcltech', 'wipro', 'tech-mahindra', 'ltimindtree', 'cognizant', 'mphasis', 'persistent-systems', 'coforge',
  'tata-motors', 'mahindra-group', 'bajaj-auto', 'tvs-motor', 'tata-steel', 'jsw-group', 'aditya-birla-group', 'reliance-industries', 'jindal-steel-power', 'larsen-toubro',
  'tata-communications', 'bharti-airtel', 'indus-towers', 'dr-reddys', 'sun-pharma', 'cipla', 'lupin', 'biocon',
  'asian-paints', 'titan-company', 'marico', 'godrej-group', 'dabur', 'tata-consumer-products'
);

insert into public.career_portals (slug, company_name, industry, career_url)
values
  ('tcs', 'Tata Consultancy Services (TCS)', 'IT Services', 'https://www.tcs.com/careers'),
  ('infosys', 'Infosys', 'IT Services', 'https://www.infosys.com/careers.html'),
  ('hcltech', 'HCLTech', 'IT Services', 'https://careers.hcltech.com/job/'),
  ('wipro', 'Wipro', 'IT Services', 'https://careers.wipro.com/'),
  ('tech-mahindra', 'Tech Mahindra', 'IT Services', 'https://careers.techmahindra.com/'),
  ('ltimindtree', 'LTIMindtree', 'IT Services', 'https://www.ltimindtree.com/careers/'),
  ('cognizant', 'Cognizant India', 'IT Services', 'https://careers.cognizant.com/'),
  ('mphasis', 'Mphasis', 'IT Services', 'https://careers.mphasis.com/'),
  ('persistent-systems', 'Persistent Systems', 'IT Services', 'https://www.persistent.com/careers/'),
  ('coforge', 'Coforge', 'IT Services', 'https://www.coforge.com/careers'),
  ('tata-motors', 'Tata Motors', 'Automotive', 'https://careers.tatamotors.com/'),
  ('mahindra-group', 'Mahindra Group', 'Conglomerate', 'https://jobs.mahindracareers.com/'),
  ('bajaj-auto', 'Bajaj Auto', 'Automotive', 'https://www.bajajauto.com/careers'),
  ('tvs-motor', 'TVS Motor', 'Automotive', 'https://www.tvsmotor.com/careers'),
  ('tata-steel', 'Tata Steel', 'Steel', 'https://www.tatasteel.com/careers/'),
  ('jsw-group', 'JSW Group', 'Diversified', 'https://www.jsw.in/careers'),
  ('aditya-birla-group', 'Aditya Birla Group', 'Conglomerate', 'https://careers.adityabirla.com/'),
  ('reliance-industries', 'Reliance Industries', 'Energy/Retail/Telecom', 'https://careers.ril.com/'),
  ('jindal-steel-power', 'Jindal Steel & Power', 'Steel', 'https://www.jindalsteelpower.com/careers.html'),
  ('larsen-toubro', 'Larsen & Toubro (L&T)', 'Engineering', 'https://careers.larsentoubro.com/'),
  ('tata-communications', 'Tata Communications', 'Telecom', 'https://www.tatacommunications.com/careers/'),
  ('bharti-airtel', 'Bharti Airtel', 'Telecom', 'https://www.airtel.com/careers'),
  ('indus-towers', 'Indus Towers', 'Telecom Infrastructure', 'https://www.industowers.com/careers'),
  ('dr-reddys', 'Dr. Reddy''s', 'Pharmaceuticals', 'https://careers.drreddys.com/'),
  ('sun-pharma', 'Sun Pharma', 'Pharmaceuticals', 'https://sunpharma.com/careers'),
  ('cipla', 'Cipla', 'Pharmaceuticals', 'https://www.cipla.com/careers'),
  ('lupin', 'Lupin', 'Pharmaceuticals', 'https://www.lupin.com/careers'),
  ('biocon', 'Biocon', 'Biotechnology', 'https://www.biocon.com/careers'),
  ('asian-paints', 'Asian Paints', 'Manufacturing', 'https://www.asianpaints.com/careers.html'),
  ('titan-company', 'Titan Company', 'Consumer Goods', 'https://www.titancompany.in/careers/'),
  ('marico', 'Marico', 'FMCG', 'https://marico.com/india/careers'),
  ('godrej-group', 'Godrej Group', 'Conglomerate', 'https://www.godrejcareers.com/'),
  ('dabur', 'Dabur', 'FMCG', 'https://www.dabur.com/careers'),
  ('tata-consumer-products', 'Tata Consumer Products', 'FMCG', 'https://www.tataconsumer.com/careers')
on conflict (slug) do update set
  company_name = excluded.company_name,
  industry = excluded.industry,
  career_url = excluded.career_url,
  is_active = true,
  updated_at = now();

insert into public.library_topics (name, brief_description, explanation, example)
values
  ('API Testing', 'Validates API behavior, contracts, responses, and error handling.', 'API testing checks the service layer directly without relying on a user interface. It verifies request methods, authentication, status codes, response schemas, validation rules, error messages, and behavior across valid and invalid inputs.', 'GET /api/users/42 should return a successful response with the expected user schema.'),
  ('Automation Testing', 'Uses scripts and tools to execute repeatable tests efficiently.', 'Automation testing is useful for stable, repeatable checks such as regression suites, API verification, and browser workflows. Good automation has clear assertions, reliable test data, useful failure output, and runs at the right level of the test pyramid.', 'expect(loginPage.heading()).toHaveText(Welcome back);'),
  ('Black-box Testing', 'Tests behavior from the outside without inspecting implementation code.', 'Black-box testing focuses on requirements and observable results. A tester supplies inputs, performs actions, and compares the result with the expected behavior without needing to know how the feature is implemented internally.', 'Invalid password input should show a validation message and prevent login.'),
  ('Boundary Value Analysis', 'Tests values at and around the edges of an accepted range.', 'Boundary value analysis targets the places where defects commonly occur: minimums, maximums, just below limits, just above limits, and empty values. It reduces test effort while covering high-risk transitions.', 'For an age range of 18 through 60, test 17, 18, 19, 59, 60, and 61.'),
  ('Exploratory Testing', 'Combines learning, test design, and execution in an adaptive session.', 'Exploratory testing does not follow only pre-written cases. The tester learns the product while testing it, follows useful observations, probes risks, and records evidence. Time-boxed charters help keep the exploration focused and repeatable.', 'Explore checkout failures with retries, refreshes, back navigation, and slow networks.'),
  ('Integration Testing', 'Checks that connected modules or services work correctly together.', 'Integration tests validate boundaries between components such as an API and database, a service and queue, or a frontend and backend. They catch incorrect contracts, data mapping issues, transaction problems, and configuration mismatches.', 'Create a user through the service and verify that the user is stored in the database.'),
  ('Load Testing', 'Measures system behavior under an expected number of concurrent users or requests.', 'Load testing models normal and peak traffic to measure response times, throughput, error rates, and resource usage. Results help identify bottlenecks before real users experience slow or failed requests.', 'Run 500 concurrent users at 100 requests per second for 10 minutes.'),
  ('Manual Testing', 'Evaluates software through deliberate human interaction and observation.', 'Manual testing is valuable for usability, visual quality, new features, exploratory work, and scenarios that are difficult to automate. It still benefits from clear scope, test data, expected results, and recorded evidence.', 'Open the profile, update the location, save it, and confirm the value remains after refresh.'),
  ('Performance Testing', 'Evaluates speed, stability, scalability, and resource use.', 'Performance testing measures how a system behaves over time and under different workloads. It includes response time, throughput, concurrency, memory, CPU, and recovery observations, not just whether a request succeeds.', 'The 95th percentile response time should remain below 500 milliseconds.'),
  ('Regression Testing', 'Confirms that existing behavior still works after a change.', 'Regression testing reruns important checks after new code, configuration, or dependency changes. A risk-based regression suite prioritizes critical user journeys and areas connected to the change.', 'The checkout regression suite should still complete a paid order after a release.'),
  ('Smoke Testing', 'Performs a short health check to decide whether a build is testable.', 'Smoke tests cover the most important paths such as launching the application, signing in, loading core data, and completing a basic action. A failed smoke test usually blocks deeper testing until the build is fixed.', 'Launch the app, sign in with a test user, and verify the home screen loads.'),
  ('Test Case Design', 'Turns requirements and risks into clear, effective test scenarios.', 'Test case design selects meaningful inputs, preconditions, actions, expected results, and cleanup. Techniques such as equivalence partitioning, boundary analysis, decision tables, and state transitions improve coverage without unnecessary duplication.', 'A test case records the precondition, action, expected result, and cleanup for an empty profile submission.'),
  ('Test-Driven Development', 'Uses a failing test, a minimal implementation, and refactoring as the development loop.', 'Test-driven development follows red, green, refactor. The test describes the desired behavior before implementation, the smallest change makes it pass, and the code is then improved while the test protects the behavior.', 'Write a test expecting add(2, 3) to equal 5, implement add, then refactor.'),
  ('Unit Testing', 'Tests a small unit of code in isolation from external dependencies.', 'Unit tests focus on a function, class, or component and run quickly with controlled inputs. Dependencies are commonly replaced with test doubles so failures point directly to the unit under test.', 'expect(formatSalary(1800000)).toBe(18 LPA);'),
  ('User Acceptance Testing', 'Confirms that a feature satisfies business goals and real user needs.', 'User acceptance testing is performed against agreed acceptance criteria, often by product owners, customers, or representative users. It validates that the complete workflow is useful and ready for release, beyond technical correctness alone.', 'A candidate applies to a recommended job and sees the application under Applied Jobs.')
on conflict (name) do update set
  brief_description = excluded.brief_description,
  explanation = excluded.explanation,
  example = excluded.example,
  is_active = true,
  updated_at = now();

insert into public.courses (title, topic, provider, level, duration, url)
values
  ('API Testing with Postman', 'API Testing', 'Postman Academy', 'Beginner', 'Self-paced', 'https://academy.postman.com/'),
  ('Automated Software Testing', 'Automation Testing', 'Coursera', 'Beginner', '4 weeks', 'https://www.coursera.org/search?query=automated%20software%20testing'),
  ('Agile with Scrum', 'Agile and Scrum', 'Scrum.org', 'Beginner', 'Self-paced', 'https://www.scrum.org/resources/what-is-scrum'),
  ('Black-box Testing Techniques', 'Black-box Testing', 'Udemy', 'Intermediate', '6 hours', 'https://www.udemy.com/courses/search/?q=black%20box%20testing'),
  ('Boundary Value Analysis and Equivalence Partitioning', 'Boundary Value Analysis', 'Guru99', 'Beginner', '2 hours', 'https://www.guru99.com/equivalence-partitioning-boundary-value-analysis.html'),
  ('Cypress End-to-End Testing', 'Cypress', 'Cypress Learn', 'Intermediate', 'Self-paced', 'https://learn.cypress.io/'),
  ('Docker for Developers', 'Docker', 'Docker', 'Beginner', 'Self-paced', 'https://www.docker.com/101-tutorial/'),
  ('Exploratory Testing Essentials', 'Exploratory Testing', 'Ministry of Testing', 'Intermediate', 'Self-paced', 'https://www.ministryoftesting.com/dojo'),
  ('Git and GitHub Fundamentals', 'Git and GitHub', 'GitHub Skills', 'Beginner', 'Self-paced', 'https://skills.github.com/'),
  ('Integration Testing with JavaScript', 'Integration Testing', 'Pluralsight', 'Intermediate', '3 hours', 'https://www.pluralsight.com/search?q=integration%20testing%20javascript'),
  ('Java Programming for Testers', 'Java', 'Codecademy', 'Beginner', '25 hours', 'https://www.codecademy.com/learn/learn-java'),
  ('JMeter Load Testing', 'Load Testing', 'Udemy', 'Intermediate', '8 hours', 'https://www.udemy.com/courses/search/?q=jmeter%20load%20testing'),
  ('Manual Testing and Test Case Design', 'Manual Testing', 'Test Automation University', 'Beginner', 'Self-paced', 'https://testautomationu.applitools.com/'),
  ('Performance Testing Fundamentals', 'Performance Testing', 'Coursera', 'Intermediate', '6 weeks', 'https://www.coursera.org/search?query=performance%20testing'),
  ('Playwright Web Testing', 'Playwright', 'Microsoft Learn', 'Intermediate', 'Self-paced', 'https://learn.microsoft.com/en-us/training/modules/build-with-playwright/'),
  ('Postman API Fundamentals Student Expert', 'Postman', 'Postman Academy', 'Beginner', 'Self-paced', 'https://academy.postman.com/path/postman-api-fundamentals-student-expert'),
  ('Python for Everybody', 'Python', 'Coursera', 'Beginner', '8 months', 'https://www.coursera.org/specializations/python'),
  ('Regression Testing Strategy', 'Regression Testing', 'Ministry of Testing', 'Intermediate', 'Self-paced', 'https://www.ministryoftesting.com/dojo'),
  ('Selenium WebDriver with Java', 'Selenium', 'Selenium Documentation', 'Intermediate', 'Self-paced', 'https://www.selenium.dev/documentation/webdriver/'),
  ('Smoke Testing and Release Readiness', 'Smoke Testing', 'Test Automation University', 'Beginner', 'Self-paced', 'https://testautomationu.applitools.com/'),
  ('SQL for Data and QA Engineers', 'SQL', 'Khan Academy', 'Beginner', 'Self-paced', 'https://www.khanacademy.org/computing/computer-programming/sql'),
  ('Test-Driven Development in JavaScript', 'Test-Driven Development', 'Pluralsight', 'Intermediate', '3 hours', 'https://www.pluralsight.com/search?q=test%20driven%20development%20javascript'),
  ('Unit Testing with Jest', 'Unit Testing', 'Jest Documentation', 'Beginner', 'Self-paced', 'https://jestjs.io/docs/getting-started'),
  ('User Acceptance Testing', 'User Acceptance Testing', 'Coursera', 'Intermediate', '4 weeks', 'https://www.coursera.org/search?query=user%20acceptance%20testing'),
  ('TypeScript for JavaScript Developers', 'TypeScript', 'Microsoft Learn', 'Intermediate', 'Self-paced', 'https://www.typescriptlang.org/docs/handbook/intro.html')
on conflict (title) do update set
  topic = excluded.topic,
  provider = excluded.provider,
  level = excluded.level,
  duration = excluded.duration,
  url = excluded.url,
  is_active = true,
  updated_at = now();
