export interface JobLearningSkill {
  name: string;
  matchers: string[];
  briefDescription: string;
  explanation: string;
  example: string;
}

export const jobLearningCatalog: JobLearningSkill[] = [
  { name: 'JavaScript', matchers: ['javascript', 'ecmascript'], briefDescription: 'A programming language used for interactive web applications and server-side services.', explanation: 'JavaScript runs in web browsers and on server runtimes such as Node.js. Job requirements commonly include asynchronous programming, modules, data handling, and working with browser or service APIs.', example: 'Use async/await to fetch profile data and render the response after it resolves.' },
  { name: 'TypeScript', matchers: ['typescript'], briefDescription: 'JavaScript with a static type system for safer application development.', explanation: 'TypeScript adds compile-time types, interfaces, and generics to JavaScript. Teams use it to make contracts explicit and catch many data-shape mistakes before code runs.', example: 'Define a Job interface so title, company, and application URL are checked by the compiler.' },
  { name: 'Python', matchers: ['python'], briefDescription: 'A general-purpose language used in backend services, automation, data, and AI.', explanation: 'Python is valued for its readable syntax and broad ecosystem. Common work includes APIs, scripts, data processing, testing, and machine-learning applications.', example: 'Write a Python service that validates incoming JSON and stores normalized records.' },
  { name: 'Java', matchers: ['java'], briefDescription: 'A strongly typed language widely used for backend and enterprise systems.', explanation: 'Java applications commonly use object-oriented design, the JVM, automated tests, and frameworks such as Spring. Roles often require building maintainable services and integrating databases or messaging systems.', example: 'Implement a Spring service that validates an order and persists it transactionally.' },
  { name: 'C++', matchers: ['c++', 'cpp'], briefDescription: 'A compiled language used where performance and low-level control matter.', explanation: 'C++ provides direct control over memory and runtime behavior while supporting abstraction and generic programming. It is common in systems software, embedded products, graphics, and performance-sensitive services.', example: 'Use RAII and smart pointers to manage a resource safely across error paths.' },
  { name: 'C#', matchers: ['c#', 'c sharp'], briefDescription: 'A modern language commonly used with .NET for services, desktop, and cloud apps.', explanation: 'C# provides static typing, async programming, and a mature .NET ecosystem. Employers often pair it with ASP.NET Core, Entity Framework, cloud hosting, and automated tests.', example: 'Build an ASP.NET Core endpoint that validates a request and returns a typed response.' },
  { name: 'React', matchers: ['react', 'react.js', 'reactjs'], briefDescription: 'A component-based JavaScript library for building user interfaces.', explanation: 'React applications compose reusable components and render from state. Relevant skills include props, state, effects, accessible controls, and managing asynchronous UI states.', example: 'Render a job list from state and show a loading state while the next page is fetched.' },
  { name: 'Angular', matchers: ['angular'], briefDescription: 'A TypeScript framework for building structured web applications.', explanation: 'Angular includes routing, dependency injection, forms, and a component model. Production work often involves RxJS, testing, and organizing applications into maintainable feature modules.', example: 'Create a typed service that retrieves jobs and exposes loading and error states.' },
  { name: 'Node.js', matchers: ['node.js', 'nodejs'], briefDescription: 'A JavaScript runtime used to build servers, APIs, and developer tools.', explanation: 'Node.js uses an event-driven runtime suited to I/O-heavy applications. Backend roles commonly cover HTTP APIs, asynchronous work, package management, security, and observability.', example: 'Create an API route that validates query parameters before reading from a database.' },
  { name: '.NET', matchers: ['.net', 'dotnet', 'asp.net'], briefDescription: 'Microsoft’s development platform for web, cloud, desktop, and service applications.', explanation: '.NET provides runtimes, libraries, and tooling for applications commonly written in C#. Backend work often uses ASP.NET Core, dependency injection, data access, and automated testing.', example: 'Register a repository with dependency injection and use it from an ASP.NET controller.' },
  { name: 'Spring Boot', matchers: ['spring boot', 'springboot'], briefDescription: 'A Java framework for creating production-ready services with minimal setup.', explanation: 'Spring Boot configures common application infrastructure and integrates with Spring MVC, data stores, security, and testing tools. Developers build APIs and services with clear dependency boundaries.', example: 'Expose a REST controller backed by a service and repository.' },
  { name: 'SQL', matchers: ['sql', 'structured query language'], briefDescription: 'A language for querying and changing data in relational databases.', explanation: 'SQL skills include filtering, joins, grouping, transactions, and understanding indexes. Strong query design helps applications return correct data efficiently.', example: 'Join users to applications, group by user, and count applications per month.' },
  { name: 'PostgreSQL', matchers: ['postgresql', 'postgres'], briefDescription: 'An open-source relational database with strong SQL and JSON support.', explanation: 'PostgreSQL provides transactions, constraints, indexes, JSONB, and extensibility. Application developers use these features to preserve data integrity and query structured or semi-structured data.', example: 'Add a unique constraint on a normalized email so duplicate accounts cannot be inserted.' },
  { name: 'MySQL', matchers: ['mysql'], briefDescription: 'A widely used relational database for web and business applications.', explanation: 'MySQL stores data in relational tables and supports transactions, indexes, and SQL queries. Job requirements often include schema design, query performance, and safe migrations.', example: 'Add an index to a frequently filtered column and compare query plans.' },
  { name: 'MongoDB', matchers: ['mongodb', 'mongo db'], briefDescription: 'A document database that stores flexible JSON-like records.', explanation: 'MongoDB groups related data into documents and supports indexes, validation, and aggregation pipelines. Engineers must choose document boundaries that support expected access patterns.', example: 'Use an aggregation pipeline to group event documents by account and day.' },
  { name: 'Redis', matchers: ['redis'], briefDescription: 'An in-memory data store used for caching, queues, and fast lookups.', explanation: 'Redis supports data structures such as strings, hashes, sets, and streams. Production use requires sensible TTLs, cache invalidation, and understanding persistence and availability trade-offs.', example: 'Cache a frequently requested profile for five minutes and invalidate it on update.' },
  { name: 'Amazon Web Services', matchers: ['aws', 'amazon web services'], briefDescription: 'A cloud platform offering compute, storage, databases, networking, and managed services.', explanation: 'AWS work involves selecting services, securing identity and network access, deploying workloads, and monitoring cost and reliability. Role requirements often name services such as S3, EC2, Lambda, or RDS.', example: 'Store uploads in a private S3 bucket and grant access through a short-lived signed URL.' },
  { name: 'Microsoft Azure', matchers: ['azure', 'microsoft azure'], briefDescription: 'Microsoft’s cloud platform for hosting applications, data, and identity services.', explanation: 'Azure provides managed compute, storage, databases, networking, and identity. Engineers commonly deploy services, configure least-privilege access, and monitor operational health.', example: 'Deploy a web API with managed identity access to a storage account.' },
  { name: 'Google Cloud Platform', matchers: ['gcp', 'google cloud', 'google cloud platform'], briefDescription: 'Google’s cloud platform for compute, data, networking, and AI services.', explanation: 'GCP work includes deploying applications, configuring IAM, connecting managed data services, and observing workloads. Service selection should match security, reliability, and cost needs.', example: 'Run a containerized API on Cloud Run with access to a managed database.' },
  { name: 'Docker', matchers: ['docker', 'docker containers'], briefDescription: 'A tool for packaging applications and dependencies into portable containers.', explanation: 'Docker images describe reproducible runtime environments. Teams use containers in local development, CI, and production while keeping images small and secrets outside the image.', example: 'Build an API image from a lockfile and run it with configuration supplied at runtime.' },
  { name: 'Kubernetes', matchers: ['kubernetes', 'k8s'], briefDescription: 'A platform for deploying and managing containerized workloads across clusters.', explanation: 'Kubernetes manages deployments, services, configuration, health checks, and scaling. Operators need to understand resource requests, rollout behavior, networking, and access control.', example: 'Deploy three API replicas with readiness probes and a rolling update strategy.' },
  { name: 'Terraform', matchers: ['terraform', 'infrastructure as code'], briefDescription: 'An infrastructure-as-code tool for defining and managing cloud resources.', explanation: 'Terraform describes infrastructure declaratively and tracks it in state. Safe workflows review plans, protect state, modularize reusable resources, and avoid committing secrets.', example: 'Define a storage bucket and its access policy, then review the plan before applying it.' },
  { name: 'Git', matchers: ['git', 'github', 'gitlab', 'version control'], briefDescription: 'A version-control system for tracking and collaborating on code changes.', explanation: 'Git records project history through commits and branches. Team workflows rely on clear commits, conflict resolution, code review, and keeping sensitive data out of repository history.', example: 'Create a feature branch, commit a focused change, and rebase it before review.' },
  { name: 'CI/CD', matchers: ['ci/cd', 'continuous integration', 'continuous delivery', 'continuous deployment'], briefDescription: 'Automated workflows that build, test, and deliver software changes.', explanation: 'CI/CD pipelines give fast feedback by running repeatable checks on every change and automating releases. Reliable pipelines protect credentials and make failures diagnosable.', example: 'Run lint, tests, and a production build before publishing a release artifact.' },
  { name: 'Linux', matchers: ['linux'], briefDescription: 'An operating system commonly used for servers, containers, and development.', explanation: 'Linux skills include navigating the filesystem, managing processes and permissions, using shell tools, and diagnosing network or service issues.', example: 'Inspect service logs and identify which process is listening on a port.' },
  { name: 'REST APIs', matchers: ['rest api', 'rest apis', 'restful api', 'restful apis'], briefDescription: 'HTTP interfaces organized around resources and standard methods.', explanation: 'REST API design uses meaningful resource URLs, HTTP methods, status codes, validation, and consistent error responses. Good APIs also consider authentication, pagination, and backward compatibility.', example: 'Use GET /jobs?limit=20&offset=20 to retrieve the next page of listings.' },
  { name: 'GraphQL', matchers: ['graphql'], briefDescription: 'A query language and runtime for clients to request structured API data.', explanation: 'GraphQL exposes a typed schema and lets clients select fields. Server design must control authorization, query complexity, resolver performance, and error behavior.', example: 'Query a job title and employer name without fetching unrelated fields.' },
  { name: 'Apache Kafka', matchers: ['kafka', 'apache kafka'], briefDescription: 'A distributed event-streaming platform for high-throughput data pipelines.', explanation: 'Kafka organizes events into topics and partitions. Engineers design producer and consumer behavior, delivery guarantees, schema evolution, and recovery from processing failures.', example: 'Publish an order-created event and let an independent service consume it.' },
  { name: 'Selenium', matchers: ['selenium', 'webdriver'], briefDescription: 'A browser automation framework for testing web applications.', explanation: 'Selenium drives browsers through WebDriver. Reliable tests use stable locators, explicit waits, isolated test data, and assertions tied to user-visible behavior.', example: 'Automate signing in and verify that the account dashboard appears.' },
  { name: 'Cypress', matchers: ['cypress'], briefDescription: 'A browser-based framework for end-to-end and component testing.', explanation: 'Cypress runs tests alongside the application and provides automatic waiting and debugging tools. Tests should use stable selectors and cover important user workflows.', example: 'Verify a candidate can filter jobs and open a matching listing.' },
  { name: 'Playwright', matchers: ['playwright'], briefDescription: 'A browser automation framework for reliable end-to-end testing.', explanation: 'Playwright controls Chromium, Firefox, and WebKit with auto-waiting, isolated browser contexts, and trace tooling. It supports robust cross-browser user-flow tests.', example: 'Test profile persistence after reload in separate authenticated browser contexts.' },
  { name: 'Jest', matchers: ['jest'], briefDescription: 'A JavaScript testing framework for unit and integration tests.', explanation: 'Jest provides assertions, mocks, and test discovery for JavaScript and TypeScript projects. Tests should verify observable behavior and isolate external dependencies where appropriate.', example: 'Mock a provider response and assert that the adapter maps its URL correctly.' },
  { name: 'JUnit', matchers: ['junit'], briefDescription: 'A testing framework for writing and running Java tests.', explanation: 'JUnit supports automated unit and integration testing with assertions, lifecycle hooks, and parameterized cases. Tests help catch regressions at the class and service boundaries.', example: 'Test that an invalid request returns a validation error without writing to the repository.' },
  { name: 'Postman', matchers: ['postman'], briefDescription: 'A platform for designing, sending, and testing HTTP API requests.', explanation: 'Postman collections organize API requests and can run assertions against status codes, response bodies, and authentication behavior. They are useful for exploratory API checks and repeatable smoke tests.', example: 'Assert that a recommendations endpoint returns a jobs array and a next-page offset.' },
  { name: 'Apache JMeter', matchers: ['jmeter', 'apache jmeter'], briefDescription: 'A tool for load and performance testing of services and applications.', explanation: 'JMeter simulates concurrent users and records throughput, latency, and errors. Useful tests model realistic traffic patterns and establish clear performance thresholds.', example: 'Run a steady API load and track the 95th-percentile response time.' },
  { name: 'Power BI', matchers: ['power bi', 'powerbi'], briefDescription: 'Microsoft’s business intelligence platform for data modeling and reports.', explanation: 'Power BI connects data sources, transforms data, builds semantic models, and presents interactive reports. Useful skills include data modeling, DAX, refresh behavior, and access control.', example: 'Create a report that compares monthly hiring volume by department.' },
  { name: 'Tableau', matchers: ['tableau'], briefDescription: 'A platform for visual analytics and interactive dashboards.', explanation: 'Tableau connects to data, builds visual analyses, and publishes dashboards. Effective work selects appropriate chart types, validates measures, and communicates trends clearly.', example: 'Build a dashboard comparing role demand by location and experience level.' },
];